config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    resources :comments, shallow: true
  end
  resources :projects
  get "dashboard/index"
  root "dashboard#index"
  devise_for :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @task = Task.find_by(:id => params[:task_id])
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @task = Task.find(params[:task_id])
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @task, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:task_id, :user_id, :description)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comments.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>User</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.task_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.description %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_task_comment_path(@task) %>

app/views/comments/_form.html.erb
<%= form_with(model: [@task, @comment], local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_id %>
    <%= form.text_field :task_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%#= form_with(model: comment, local: true) do |form| %>
  <%# if comment.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>-->

<!--      <ul>-->
      <%# comment.errors.full_messages.each do |message| %>
<!--        <li><%#= message %></li>-->
      <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <div class="field">-->
    <%#= form.label :task_id %>
    <%#= form.text_field :task_id %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :user_id %>
    <%#= form.text_field :user_id %>
<!--  </div>-->

<!--  <div class="field">-->
    <%#= form.label :description %>
    <%#= form.text_area :description %>
<!--  </div>-->

<!--  <div class="actions">-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comment_path(@comment) %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>User</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.task_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.description %></td>
        <td><%= link_to 'Show', comment %></td>
<!--        <td><%#= link_to 'Edit', edit_comment_path(comment) %></td>-->
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', task_path(@task) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @comment.task_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @comment.description %>
</p>

<!--<%#= link_to 'Edit', edit_comment_path(@comment) %> |-->
<%#= link_to 'Back', comments_path %>