config/routes.rb
Rails.application.routes.draw do
  resources :tasks do
    resources :comments, shallow: true
  end
  resources :projects
  get "dashboard/index"
  root "dashboard#index"
  devise_for :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    if user.is_admin?
      can :create, Team
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
end

app/models/file_attachment.rb
class FileAttachment < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/models/priority.rb
class Priority < ApplicationRecord
  has_many :tasks
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  has_and_belongs_to_many :teams
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_many :comments
  has_many :file_attachments
  belongs_to :category
  belongs_to :priority
  belongs_to :status


end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team_users
  has_many :users, through: :team_users
  has_and_belongs_to_many :projects
end

app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/user.rb
class User < ApplicationRecord
  has_many :team_users
  has_many :teams, through: :team_users
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  def after_database_authentication

  end

end

app/controllers/secured_controller.rb
class SecuredController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/tasks_controller.rb
class TasksController < SecuredController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show

    # unless current_user.is_admin
    #   disable fields, use display only
    # end

    @comments = Comment.where("task_id = '#{@task.id}'")
    #
    #
    # //puts @comments
    puts 'Chancellor is coming to town'


  end

  # GET /tasks/new
  def new
    @task = Task.new
    @task.project_id = params[:project_id]
    @task.user_id = current_user.id
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:project_id, :user_id, :name, :description, :due_date, :created_at, :updated_at, :category_id, :priority_id, :status_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/secured_helper.rb
module SecuredHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskMaster</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :pagescripts %>

  </head>

  <body>
  <div class="container">
    <div class="row page-header">
      <div class="col-lg-2 bg-dark" style="vertical-align: center"><center><p>Logo Here..</p></center></div>
      <div class="col-lg-10 bg-dark">
        <nav style="float:right" class="navbar navbar-expand-sm"">
          <ul class="navbar-nav >
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, class: 'nav-link text-white' %>
            </li>
          </ul>
        </nav>
        <nav class="navbar navbar-expand-sm" style="padding-left:0">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Home', dashboard_index_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Projects', projects_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Tasks', tasks_path, class: 'nav-link text-white' %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12 bg-secondary" style="text-align:right"><span style="padding-right:21px">Welcome <b><%= current_user.email %></b></span></div>
    </div>
    <div class="row">
      <div class="col-lg-2 bg-success">
        <nav class="navbar">
          <!-- Links -->
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'New Project', new_project_path, class: 'nav-link text-white' %>
            </li>
            <li class="nav-item">
              <%= link_to 'New Task', new_task_path, class: 'nav-link text-white' %>
            </li>
        </nav>
      </div>
      <div class="col-lg-10">
        <%= yield %>
      </div>
    </div>
    <div class="row page-footer">
      <div class="col-lg-12 bg-light">
        <br>
        <center>Copyright &nbsp;&copy;</center>
        <br>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskMaster Devise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <div class="row page-header">
      <div class="col-lg-12">
        Welcome to TaskMaster
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <%= yield %>
      </div>
    </div>
    <div class="row page-footer">
      <div class="col-lg-12">
        <center>Copyright &nbsp;&copy;</center>
      </div>
    </div>
  </div>
  </body>
</html>